const events = {

  WINDOW_RESIZE: 'WINDOW_RESIZE',
  WINDOW_ON_FOCUS: 'WINDOW_ON_FOCUS',
  WINDOW_ON_BLUR: 'WINDOW_ON_BLUR',
  WINDOW_ON_MOUSEMOVE: 'WINDOW_ON_MOUSEMOVE',

  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',

  RESSOURCES_PROGRESS: 'RESSOURCES_PROGRESS',
  RESOURCES_READY: 'RESOURCES_READY',

  APP_START: 'APP_START'

}

export default events