const EventsConstants = {

  WINDOW_RESIZE: 'WINDOW_RESIZE',
  WINDOW_ON_FOCUS: 'WINDOW_ON_FOCUS',
  WINDOW_ON_BLUR: 'WINDOW_ON_BLUR',
  WINDOW_ON_MOUSEMOVE: 'WINDOW_ON_MOUSEMOVE',

  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',

  RESOURCES_PROGRESS: 'RESOURCES_PROGRESS',
  RESOURCES_READY: 'RESOURCES_READY',

  APP_START: 'APP_START',
  ROUTE_CHANGED: 'ROUTE_CHANGED'

}

export default EventsConstants